[package]
name = "ventus-dynamics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ventus-units = { path = "../ventus-units" }
libm = "0.2"
ventus-atmos = { path = "../ventus-atmos" }
ventus-aero = { path = "../ventus-aero" }
ventus-mass = { path = "../ventus-mass" }
ventus-propulsion = { path = "../ventus-propulsion" }

[dev-dependencies]
ventus-validate = { path = "../ventus-validate" }
