[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ventus-atmos = { path = "../ventus-atmos" }
ventus-gasdyn = { path = "../ventus-gasdyn" }
ventus-validate = { path = "../ventus-validate" }
serde.workspace = true
toml.workspace  = true
