[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ventus-atmos = { path = "../ventus-atmos" }
ventus-gasdyn = { path = "../ventus-gasdyn" }
ventus-aero = { path = "../ventus-aero" }
ventus-thermal = { path = "../ventus-thermal" }
ventus-inlet = { path = "../ventus-inlet" }
ventus-propulsion = { path = "../ventus-propulsion" }
ventus-mass = { path = "../ventus-mass" }
ventus-cost = { path = "../ventus-cost" }
ventus-envelope = { path = "../ventus-envelope" }
ventus-units = { path = "../ventus-units" }
ventus-fsw = { path = "../ventus-fsw" }
ventus-validate = { path = "../ventus-validate" }
serde.workspace = true
serialport.workspace = true
toml.workspace  = true

[lints]
workspace = true
