[package]
name = "ventus-inlet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ventus-units = { path = "../ventus-units" }
libm = "0.2"
ventus-gasdyn = { path = "../ventus-gasdyn" }
ventus-atmos = { path = "../ventus-atmos" }

[dev-dependencies]
ventus-validate = { path = "../ventus-validate" }

[lints]
workspace = true
