"""Generate crates/ventus-gasdyn/cases/naca1135.toml.

The expected values are RECITED from NACA Report 1135 and marked [TO VERIFY].
This script does not invent them; what it computes is the TOLERANCE each one
deserves, from the number of significant figures actually written down:

    admissible relative error = 0.5 * 10^-(sf-1) / mantissa

That denominator matters. A value with mantissa 1.4 tolerates six times more
relative error at the same digit count than one with mantissa 8.8, and using a
single round tolerance for a whole table silently excuses real disagreement in
the high-mantissa entries. This project has already been bitten by exactly that
in the M1 density cases.

One case per (Mach, quantity) rather than one per Mach, for the same reason: a
group tolerance is the loosest of its members and would weaken every other check
in the group.

Run:  python analysis/gen_naca1135_cases.py
"""

import math
import pathlib

GAMMA = 1.4

# Recited from NACA Report 1135, normal-shock and Prandtl-Meyer tables.
# (value, significant figures as printed, optional note)
RECITED = {
    1.5: {
        "pressure_ratio": (2.4583, 5, None),
        "temperature_ratio": (1.3202, 5, None),
        "mach_downstream": (0.70109, 5, None),
        "stagnation_pressure_ratio": (0.92979, 5, None),
        "prandtl_meyer_deg": (11.905, 5, None),
    },
    2.0: {
        "pressure_ratio": (4.5000, 5, "exactly 4.5 = (2*1.4*4 - 0.4)/2.4, a rational"),
        "temperature_ratio": (1.6875, 5, "exactly 27/16, a rational"),
        "mach_downstream": (0.57735, 5, "1/sqrt(3)"),
        "stagnation_pressure_ratio": (0.72087, 5, None),
        "prandtl_meyer_deg": (26.380, 5, None),
    },
    3.0: {
        "pressure_ratio": (10.333, 5, "exactly 31/3"),
        "temperature_ratio": (2.6790, 5, None),
        "mach_downstream": (0.47519, 5, None),
        "stagnation_pressure_ratio": (0.32834, 5, None),
        "prandtl_meyer_deg": (49.757, 5, None),
    },
    3.5: {
        "pressure_ratio": (14.125, 5, "exactly 113/8, a rational"),
        "temperature_ratio": (
            3.315,
            4,
            "FOUR figures, not five. The exact value is 3.3150510, which sits "
            "almost exactly on the rounding boundary of the fifth significant "
            "figure: 3.3150 and 3.3151 are each about 1.5e-5 away, and the "
            "admissible error for five figures here is 1.51e-5. The fifth digit "
            "therefore cannot be checked against a recited value at all, so it "
            "is not asserted. Checking four figures is honest; checking five "
            "would be checking my memory of a coin flip.",
        ),
        "mach_downstream": (0.45115, 5, None),
        "stagnation_pressure_ratio": (0.21295, 5, None),
        "prandtl_meyer_deg": (58.530, 5, None),
    },
}


def normal_shock(m, g=GAMMA):
    m2 = m * m
    pressure = (2 * g * m2 - (g - 1)) / (g + 1)
    density = (g + 1) * m2 / ((g - 1) * m2 + 2)
    mach_down = math.sqrt((1 + 0.5 * (g - 1) * m2) / (g * m2 - 0.5 * (g - 1)))
    p0 = (density ** (g / (g - 1))) * (((g + 1) / (2 * g * m2 - (g - 1))) ** (1 / (g - 1)))
    return {
        "pressure_ratio": pressure,
        "temperature_ratio": pressure / density,
        "density_ratio": density,
        "mach_downstream": mach_down,
        "stagnation_pressure_ratio": p0,
    }


def prandtl_meyer_deg(m, g=GAMMA):
    k = math.sqrt((g + 1) / (g - 1))
    b = math.sqrt(m * m - 1)
    return math.degrees(k * math.atan(b / k) - math.atan(b))


def tolerance(value, sig_figs):
    mantissa = value / 10 ** math.floor(math.log10(abs(value)))
    return 0.5 * 10 ** -(sig_figs - 1) / mantissa


def main():
    out = [
        "# M2 - NACA Report 1135, normal shock and Prandtl-Meyer tables, gamma = 1.4.",
        "#",
        "# GENERATED by analysis/gen_naca1135_cases.py - do not hand-edit.",
        "#",
        "# Expected values are RECITED from the report and carry [TO VERIFY]. The",
        "# tolerances are derived per value from the number of significant figures",
        "# printed: 0.5 * 10^-(sf-1) / mantissa. That denominator is not decoration -",
        "# at five figures a mantissa of 8.8 admits 5.7e-7 while a mantissa of 1.4",
        "# admits 3.5e-6, six times more. A single round tolerance for the whole table",
        "# would excuse real disagreement in the high-mantissa entries.",
        "#",
        "# One case per (Mach, quantity): a grouped case can only carry the loosest",
        "# tolerance of its members, which would weaken every other check in the group.",
        "#",
        "# These table checks are the SECOND line of validation. The first is the set",
        "# of analytic identities in the unit tests - the Prandtl relation M1*.M2* = 1,",
        "# conservation across the jump, the M -> 1 and M -> infinity limits, the",
        "# oblique-to-normal reduction, and the theta-beta-M closed form checked",
        "# against bisection. Those depend on no recited number at all.",
        "",
    ]

    worst = []
    for mach in sorted(RECITED):
        exact = normal_shock(mach)
        exact["prandtl_meyer_deg"] = prandtl_meyer_deg(mach)
        for quantity, (value, sig_figs, note) in RECITED[mach].items():
            tol = tolerance(value, sig_figs)
            gap = abs(exact[quantity] - value) / value
            worst.append((gap / tol, mach, quantity, gap, tol))

            table = "Prandtl-Meyer" if quantity == "prandtl_meyer_deg" else "normal shock"
            reason = [
                f"Recited to {sig_figs} significant figures, so the admissible relative",
                f"error is {tol:.2e}. The implementation is {gap:.2e} away, using",
                f"{gap / tol * 100:.0f} % of that budget.",
            ]
            if note:
                reason += ["", note]

            out += [
                "[[case]]",
                f'name    = "naca1135_{table.split()[0].lower()}_m{str(mach).replace(".", "p")}_{quantity}"',
                f'source  = "NACA Report 1135, {table} table, M1 = {mach}, gamma = 1.4 [TO VERIFY against a primary copy]"',
                'reason  = """',
                "\n".join(reason),
                '"""',
                f"inputs  = {{ mach = {mach}, gamma = {GAMMA} }}",
                f"expect  = {{ {quantity} = {value} }}",
                f"rel_tol = {tol:.3e}",
                "",
            ]

    pathlib.Path("crates/ventus-gasdyn/cases/naca1135.toml").write_text(
        "\n".join(out), encoding="utf-8"
    )

    worst.sort(reverse=True)
    print(f"wrote {len(worst)} cases")
    print("tightest margins (fraction of tolerance budget used):")
    for frac, mach, quantity, gap, tol in worst[:5]:
        flag = "  <-- FAILS" if frac > 1.0 else ""
        print(f"  M={mach:<4} {quantity:28} gap {gap:.2e} / tol {tol:.2e} = {frac:5.1%}{flag}")


if __name__ == "__main__":
    main()
